// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/4itosik/feedium/internal/ent/post"
	"github.com/4itosik/feedium/internal/ent/schema"
	"github.com/4itosik/feedium/internal/ent/source"
	"github.com/4itosik/feedium/internal/ent/summary"
	"github.com/4itosik/feedium/internal/ent/summaryevent"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescExternalID is the schema descriptor for external_id field.
	postDescExternalID := postFields[2].Descriptor()
	// post.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	post.ExternalIDValidator = postDescExternalID.Validators[0].(func(string) error)
	// postDescText is the schema descriptor for text field.
	postDescText := postFields[5].Descriptor()
	// post.TextValidator is a validator for the "text" field. It is called by the builders before save.
	post.TextValidator = postDescText.Validators[0].(func(string) error)
	// postDescMetadata is the schema descriptor for metadata field.
	postDescMetadata := postFields[6].Descriptor()
	// post.DefaultMetadata holds the default value on creation for the metadata field.
	post.DefaultMetadata = postDescMetadata.Default.(map[string]string)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[7].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[8].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescID is the schema descriptor for id field.
	postDescID := postFields[0].Descriptor()
	// post.DefaultID holds the default value on creation for the id field.
	post.DefaultID = postDescID.Default.(func() uuid.UUID)
	sourceFields := schema.Source{}.Fields()
	_ = sourceFields
	// sourceDescType is the schema descriptor for type field.
	sourceDescType := sourceFields[1].Descriptor()
	// source.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	source.TypeValidator = sourceDescType.Validators[0].(func(string) error)
	// sourceDescCreatedAt is the schema descriptor for created_at field.
	sourceDescCreatedAt := sourceFields[3].Descriptor()
	// source.DefaultCreatedAt holds the default value on creation for the created_at field.
	source.DefaultCreatedAt = sourceDescCreatedAt.Default.(func() time.Time)
	// sourceDescUpdatedAt is the schema descriptor for updated_at field.
	sourceDescUpdatedAt := sourceFields[4].Descriptor()
	// source.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	source.DefaultUpdatedAt = sourceDescUpdatedAt.Default.(func() time.Time)
	// source.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	source.UpdateDefaultUpdatedAt = sourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sourceDescID is the schema descriptor for id field.
	sourceDescID := sourceFields[0].Descriptor()
	// source.DefaultID holds the default value on creation for the id field.
	source.DefaultID = sourceDescID.Default.(func() uuid.UUID)
	summaryFields := schema.Summary{}.Fields()
	_ = summaryFields
	// summaryDescText is the schema descriptor for text field.
	summaryDescText := summaryFields[3].Descriptor()
	// summary.TextValidator is a validator for the "text" field. It is called by the builders before save.
	summary.TextValidator = summaryDescText.Validators[0].(func(string) error)
	// summaryDescCreatedAt is the schema descriptor for created_at field.
	summaryDescCreatedAt := summaryFields[5].Descriptor()
	// summary.DefaultCreatedAt holds the default value on creation for the created_at field.
	summary.DefaultCreatedAt = summaryDescCreatedAt.Default.(func() time.Time)
	// summaryDescID is the schema descriptor for id field.
	summaryDescID := summaryFields[0].Descriptor()
	// summary.DefaultID holds the default value on creation for the id field.
	summary.DefaultID = summaryDescID.Default.(func() uuid.UUID)
	summaryeventFields := schema.SummaryEvent{}.Fields()
	_ = summaryeventFields
	// summaryeventDescEventType is the schema descriptor for event_type field.
	summaryeventDescEventType := summaryeventFields[3].Descriptor()
	// summaryevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	summaryevent.EventTypeValidator = summaryeventDescEventType.Validators[0].(func(string) error)
	// summaryeventDescStatus is the schema descriptor for status field.
	summaryeventDescStatus := summaryeventFields[4].Descriptor()
	// summaryevent.DefaultStatus holds the default value on creation for the status field.
	summaryevent.DefaultStatus = summaryeventDescStatus.Default.(string)
	// summaryevent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	summaryevent.StatusValidator = summaryeventDescStatus.Validators[0].(func(string) error)
	// summaryeventDescCreatedAt is the schema descriptor for created_at field.
	summaryeventDescCreatedAt := summaryeventFields[7].Descriptor()
	// summaryevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	summaryevent.DefaultCreatedAt = summaryeventDescCreatedAt.Default.(func() time.Time)
	// summaryeventDescID is the schema descriptor for id field.
	summaryeventDescID := summaryeventFields[0].Descriptor()
	// summaryevent.DefaultID holds the default value on creation for the id field.
	summaryevent.DefaultID = summaryeventDescID.Default.(func() uuid.UUID)
}
