// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/4itosik/feedium/internal/ent/schema"
	"github.com/4itosik/feedium/internal/ent/source"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sourceFields := schema.Source{}.Fields()
	_ = sourceFields
	// sourceDescType is the schema descriptor for type field.
	sourceDescType := sourceFields[1].Descriptor()
	// source.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	source.TypeValidator = sourceDescType.Validators[0].(func(string) error)
	// sourceDescCreatedAt is the schema descriptor for created_at field.
	sourceDescCreatedAt := sourceFields[3].Descriptor()
	// source.DefaultCreatedAt holds the default value on creation for the created_at field.
	source.DefaultCreatedAt = sourceDescCreatedAt.Default.(func() time.Time)
	// sourceDescUpdatedAt is the schema descriptor for updated_at field.
	sourceDescUpdatedAt := sourceFields[4].Descriptor()
	// source.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	source.DefaultUpdatedAt = sourceDescUpdatedAt.Default.(func() time.Time)
	// source.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	source.UpdateDefaultUpdatedAt = sourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sourceDescID is the schema descriptor for id field.
	sourceDescID := sourceFields[0].Descriptor()
	// source.DefaultID holds the default value on creation for the id field.
	source.DefaultID = sourceDescID.Default.(func() uuid.UUID)
}
