// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/4itosik/feedium/internal/ent/post"
	"github.com/4itosik/feedium/internal/ent/predicate"
	"github.com/4itosik/feedium/internal/ent/source"
	"github.com/4itosik/feedium/internal/ent/summary"
	"github.com/4itosik/feedium/internal/ent/summaryevent"
	"github.com/google/uuid"
)

// SourceUpdate is the builder for updating Source entities.
type SourceUpdate struct {
	config
	hooks    []Hook
	mutation *SourceMutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdate) Where(ps ...predicate.Source) *SourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *SourceUpdate) SetType(v string) *SourceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableType(v *string) *SourceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *SourceUpdate) SetConfig(v map[string]interface{}) *SourceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdate) SetUpdatedAt(v time.Time) *SourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *SourceUpdate) AddPostIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *SourceUpdate) AddPosts(v ...*Post) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// AddSourceSummaryIDs adds the "source_summaries" edge to the Summary entity by IDs.
func (_u *SourceUpdate) AddSourceSummaryIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.AddSourceSummaryIDs(ids...)
	return _u
}

// AddSourceSummaries adds the "source_summaries" edges to the Summary entity.
func (_u *SourceUpdate) AddSourceSummaries(v ...*Summary) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceSummaryIDs(ids...)
}

// AddSummaryEventIDs adds the "summary_events" edge to the SummaryEvent entity by IDs.
func (_u *SourceUpdate) AddSummaryEventIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.AddSummaryEventIDs(ids...)
	return _u
}

// AddSummaryEvents adds the "summary_events" edges to the SummaryEvent entity.
func (_u *SourceUpdate) AddSummaryEvents(v ...*SummaryEvent) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSummaryEventIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdate) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *SourceUpdate) ClearPosts() *SourceUpdate {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *SourceUpdate) RemovePostIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *SourceUpdate) RemovePosts(v ...*Post) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// ClearSourceSummaries clears all "source_summaries" edges to the Summary entity.
func (_u *SourceUpdate) ClearSourceSummaries() *SourceUpdate {
	_u.mutation.ClearSourceSummaries()
	return _u
}

// RemoveSourceSummaryIDs removes the "source_summaries" edge to Summary entities by IDs.
func (_u *SourceUpdate) RemoveSourceSummaryIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.RemoveSourceSummaryIDs(ids...)
	return _u
}

// RemoveSourceSummaries removes "source_summaries" edges to Summary entities.
func (_u *SourceUpdate) RemoveSourceSummaries(v ...*Summary) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceSummaryIDs(ids...)
}

// ClearSummaryEvents clears all "summary_events" edges to the SummaryEvent entity.
func (_u *SourceUpdate) ClearSummaryEvents() *SourceUpdate {
	_u.mutation.ClearSummaryEvents()
	return _u
}

// RemoveSummaryEventIDs removes the "summary_events" edge to SummaryEvent entities by IDs.
func (_u *SourceUpdate) RemoveSummaryEventIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.RemoveSummaryEventIDs(ids...)
	return _u
}

// RemoveSummaryEvents removes "summary_events" edges to SummaryEvent entities.
func (_u *SourceUpdate) RemoveSummaryEvents(v ...*SummaryEvent) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSummaryEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := source.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Source.type": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(source.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.PostsTable,
			Columns: []string{source.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.PostsTable,
			Columns: []string{source.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.PostsTable,
			Columns: []string{source.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SourceSummariesTable,
			Columns: []string{source.SourceSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourceSummariesIDs(); len(nodes) > 0 && !_u.mutation.SourceSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SourceSummariesTable,
			Columns: []string{source.SourceSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceSummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SourceSummariesTable,
			Columns: []string{source.SourceSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SummaryEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SummaryEventsTable,
			Columns: []string{source.SummaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSummaryEventsIDs(); len(nodes) > 0 && !_u.mutation.SummaryEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SummaryEventsTable,
			Columns: []string{source.SummaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SummaryEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SummaryEventsTable,
			Columns: []string{source.SummaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceUpdateOne is the builder for updating a single Source entity.
type SourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceMutation
}

// SetType sets the "type" field.
func (_u *SourceUpdateOne) SetType(v string) *SourceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableType(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *SourceUpdateOne) SetConfig(v map[string]interface{}) *SourceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdateOne) SetUpdatedAt(v time.Time) *SourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *SourceUpdateOne) AddPostIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *SourceUpdateOne) AddPosts(v ...*Post) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// AddSourceSummaryIDs adds the "source_summaries" edge to the Summary entity by IDs.
func (_u *SourceUpdateOne) AddSourceSummaryIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.AddSourceSummaryIDs(ids...)
	return _u
}

// AddSourceSummaries adds the "source_summaries" edges to the Summary entity.
func (_u *SourceUpdateOne) AddSourceSummaries(v ...*Summary) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceSummaryIDs(ids...)
}

// AddSummaryEventIDs adds the "summary_events" edge to the SummaryEvent entity by IDs.
func (_u *SourceUpdateOne) AddSummaryEventIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.AddSummaryEventIDs(ids...)
	return _u
}

// AddSummaryEvents adds the "summary_events" edges to the SummaryEvent entity.
func (_u *SourceUpdateOne) AddSummaryEvents(v ...*SummaryEvent) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSummaryEventIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdateOne) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *SourceUpdateOne) ClearPosts() *SourceUpdateOne {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *SourceUpdateOne) RemovePostIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *SourceUpdateOne) RemovePosts(v ...*Post) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// ClearSourceSummaries clears all "source_summaries" edges to the Summary entity.
func (_u *SourceUpdateOne) ClearSourceSummaries() *SourceUpdateOne {
	_u.mutation.ClearSourceSummaries()
	return _u
}

// RemoveSourceSummaryIDs removes the "source_summaries" edge to Summary entities by IDs.
func (_u *SourceUpdateOne) RemoveSourceSummaryIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.RemoveSourceSummaryIDs(ids...)
	return _u
}

// RemoveSourceSummaries removes "source_summaries" edges to Summary entities.
func (_u *SourceUpdateOne) RemoveSourceSummaries(v ...*Summary) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceSummaryIDs(ids...)
}

// ClearSummaryEvents clears all "summary_events" edges to the SummaryEvent entity.
func (_u *SourceUpdateOne) ClearSummaryEvents() *SourceUpdateOne {
	_u.mutation.ClearSummaryEvents()
	return _u
}

// RemoveSummaryEventIDs removes the "summary_events" edge to SummaryEvent entities by IDs.
func (_u *SourceUpdateOne) RemoveSummaryEventIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.RemoveSummaryEventIDs(ids...)
	return _u
}

// RemoveSummaryEvents removes "summary_events" edges to SummaryEvent entities.
func (_u *SourceUpdateOne) RemoveSummaryEvents(v ...*SummaryEvent) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSummaryEventIDs(ids...)
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdateOne) Where(ps ...predicate.Source) *SourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceUpdateOne) Select(field string, fields ...string) *SourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Source entity.
func (_u *SourceUpdateOne) Save(ctx context.Context) (*Source, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdateOne) SaveX(ctx context.Context) *Source {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := source.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Source.type": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdateOne) sqlSave(ctx context.Context) (_node *Source, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Source.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, source.FieldID)
		for _, f := range fields {
			if !source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(source.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.PostsTable,
			Columns: []string{source.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.PostsTable,
			Columns: []string{source.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.PostsTable,
			Columns: []string{source.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SourceSummariesTable,
			Columns: []string{source.SourceSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourceSummariesIDs(); len(nodes) > 0 && !_u.mutation.SourceSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SourceSummariesTable,
			Columns: []string{source.SourceSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceSummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SourceSummariesTable,
			Columns: []string{source.SourceSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SummaryEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SummaryEventsTable,
			Columns: []string{source.SummaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSummaryEventsIDs(); len(nodes) > 0 && !_u.mutation.SummaryEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SummaryEventsTable,
			Columns: []string{source.SummaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SummaryEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.SummaryEventsTable,
			Columns: []string{source.SummaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Source{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
