// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/4itosik/feedium/internal/ent/post"
	"github.com/4itosik/feedium/internal/ent/source"
	"github.com/4itosik/feedium/internal/ent/summary"
	"github.com/google/uuid"
)

// Summary is the model entity for the Summary schema.
type Summary struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID *uuid.UUID `json:"post_id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID uuid.UUID `json:"source_id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// WordCount holds the value of the "word_count" field.
	WordCount int `json:"word_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SummaryQuery when eager-loading is set.
	Edges        SummaryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SummaryEdges holds the relations/edges for other nodes in the graph.
type SummaryEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// Source holds the value of the source edge.
	Source *Source `json:"source,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SummaryEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SummaryEdges) SourceOrErr() (*Source, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: source.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Summary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case summary.FieldPostID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case summary.FieldWordCount:
			values[i] = new(sql.NullInt64)
		case summary.FieldText:
			values[i] = new(sql.NullString)
		case summary.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case summary.FieldID, summary.FieldSourceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Summary fields.
func (_m *Summary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case summary.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case summary.FieldPostID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				_m.PostID = new(uuid.UUID)
				*_m.PostID = *value.S.(*uuid.UUID)
			}
		case summary.FieldSourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value != nil {
				_m.SourceID = *value
			}
		case summary.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case summary.FieldWordCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field word_count", values[i])
			} else if value.Valid {
				_m.WordCount = int(value.Int64)
			}
		case summary.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Summary.
// This includes values selected through modifiers, order, etc.
func (_m *Summary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the Summary entity.
func (_m *Summary) QueryPost() *PostQuery {
	return NewSummaryClient(_m.config).QueryPost(_m)
}

// QuerySource queries the "source" edge of the Summary entity.
func (_m *Summary) QuerySource() *SourceQuery {
	return NewSummaryClient(_m.config).QuerySource(_m)
}

// Update returns a builder for updating this Summary.
// Note that you need to call Summary.Unwrap() before calling this method if this Summary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Summary) Update() *SummaryUpdateOne {
	return NewSummaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Summary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Summary) Unwrap() *Summary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Summary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Summary) String() string {
	var builder strings.Builder
	builder.WriteString("Summary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.PostID; v != nil {
		builder.WriteString("post_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("word_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.WordCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Summaries is a parsable slice of Summary.
type Summaries []*Summary
