// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/4itosik/feedium/internal/ent/predicate"
	"github.com/4itosik/feedium/internal/ent/summaryevent"
)

// SummaryEventDelete is the builder for deleting a SummaryEvent entity.
type SummaryEventDelete struct {
	config
	hooks    []Hook
	mutation *SummaryEventMutation
}

// Where appends a list predicates to the SummaryEventDelete builder.
func (_d *SummaryEventDelete) Where(ps ...predicate.SummaryEvent) *SummaryEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SummaryEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SummaryEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SummaryEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(summaryevent.Table, sqlgraph.NewFieldSpec(summaryevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SummaryEventDeleteOne is the builder for deleting a single SummaryEvent entity.
type SummaryEventDeleteOne struct {
	_d *SummaryEventDelete
}

// Where appends a list predicates to the SummaryEventDelete builder.
func (_d *SummaryEventDeleteOne) Where(ps ...predicate.SummaryEvent) *SummaryEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SummaryEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{summaryevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SummaryEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
