// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/4itosik/feedium/api/feedium (interfaces: SourceServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=cmd/feediumctl/internal/app/mock/mock_source_client.go -package=mock github.com/4itosik/feedium/api/feedium SourceServiceClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	feedium "github.com/4itosik/feedium/api/feedium"
)

// MockSourceServiceClient is a mock of SourceServiceClient interface.
type MockSourceServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSourceServiceClientMockRecorder
	isgomock struct{}
}

// MockSourceServiceClientMockRecorder is the mock recorder for MockSourceServiceClient.
type MockSourceServiceClientMockRecorder struct {
	mock *MockSourceServiceClient
}

// NewMockSourceServiceClient creates a new mock instance.
func NewMockSourceServiceClient(ctrl *gomock.Controller) *MockSourceServiceClient {
	mock := &MockSourceServiceClient{ctrl: ctrl}
	mock.recorder = &MockSourceServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceServiceClient) EXPECT() *MockSourceServiceClientMockRecorder {
	return m.recorder
}

// V1CreateSource mocks base method.
func (m *MockSourceServiceClient) V1CreateSource(ctx context.Context, in *feedium.V1CreateSourceRequest, opts ...grpc.CallOption) (*feedium.V1CreateSourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "V1CreateSource", varargs...)
	ret0, _ := ret[0].(*feedium.V1CreateSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// V1CreateSource indicates an expected call of V1CreateSource.
func (mr *MockSourceServiceClientMockRecorder) V1CreateSource(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1CreateSource", reflect.TypeOf((*MockSourceServiceClient)(nil).V1CreateSource), varargs...)
}

// V1DeleteSource mocks base method.
func (m *MockSourceServiceClient) V1DeleteSource(ctx context.Context, in *feedium.V1DeleteSourceRequest, opts ...grpc.CallOption) (*feedium.V1DeleteSourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "V1DeleteSource", varargs...)
	ret0, _ := ret[0].(*feedium.V1DeleteSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// V1DeleteSource indicates an expected call of V1DeleteSource.
func (mr *MockSourceServiceClientMockRecorder) V1DeleteSource(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1DeleteSource", reflect.TypeOf((*MockSourceServiceClient)(nil).V1DeleteSource), varargs...)
}

// V1GetSource mocks base method.
func (m *MockSourceServiceClient) V1GetSource(ctx context.Context, in *feedium.V1GetSourceRequest, opts ...grpc.CallOption) (*feedium.V1GetSourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "V1GetSource", varargs...)
	ret0, _ := ret[0].(*feedium.V1GetSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// V1GetSource indicates an expected call of V1GetSource.
func (mr *MockSourceServiceClientMockRecorder) V1GetSource(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1GetSource", reflect.TypeOf((*MockSourceServiceClient)(nil).V1GetSource), varargs...)
}

// V1ListSources mocks base method.
func (m *MockSourceServiceClient) V1ListSources(ctx context.Context, in *feedium.V1ListSourcesRequest, opts ...grpc.CallOption) (*feedium.V1ListSourcesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "V1ListSources", varargs...)
	ret0, _ := ret[0].(*feedium.V1ListSourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// V1ListSources indicates an expected call of V1ListSources.
func (mr *MockSourceServiceClientMockRecorder) V1ListSources(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1ListSources", reflect.TypeOf((*MockSourceServiceClient)(nil).V1ListSources), varargs...)
}

// V1UpdateSource mocks base method.
func (m *MockSourceServiceClient) V1UpdateSource(ctx context.Context, in *feedium.V1UpdateSourceRequest, opts ...grpc.CallOption) (*feedium.V1UpdateSourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "V1UpdateSource", varargs...)
	ret0, _ := ret[0].(*feedium.V1UpdateSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// V1UpdateSource indicates an expected call of V1UpdateSource.
func (mr *MockSourceServiceClientMockRecorder) V1UpdateSource(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1UpdateSource", reflect.TypeOf((*MockSourceServiceClient)(nil).V1UpdateSource), varargs...)
}
