// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/4itosik/feedium/internal/service/summary (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/summary/mock/mock_summary.go -package=mock github.com/4itosik/feedium/internal/service/summary Usecase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	biz "github.com/4itosik/feedium/internal/biz"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetSummary mocks base method.
func (m *MockUsecase) GetSummary(ctx context.Context, id string) (biz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, id)
	ret0, _ := ret[0].(biz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockUsecaseMockRecorder) GetSummary(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockUsecase)(nil).GetSummary), ctx, id)
}

// GetSummaryEvent mocks base method.
func (m *MockUsecase) GetSummaryEvent(ctx context.Context, id string) (*biz.SummaryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryEvent", ctx, id)
	ret0, _ := ret[0].(*biz.SummaryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryEvent indicates an expected call of GetSummaryEvent.
func (mr *MockUsecaseMockRecorder) GetSummaryEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryEvent", reflect.TypeOf((*MockUsecase)(nil).GetSummaryEvent), ctx, id)
}

// ListPostSummaries mocks base method.
func (m *MockUsecase) ListPostSummaries(ctx context.Context, postID string) ([]biz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostSummaries", ctx, postID)
	ret0, _ := ret[0].([]biz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostSummaries indicates an expected call of ListPostSummaries.
func (mr *MockUsecaseMockRecorder) ListPostSummaries(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostSummaries", reflect.TypeOf((*MockUsecase)(nil).ListPostSummaries), ctx, postID)
}

// ListSourceSummaries mocks base method.
func (m *MockUsecase) ListSourceSummaries(ctx context.Context, sourceID string, pageSize int, pageToken string) (biz.ListSummariesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSourceSummaries", ctx, sourceID, pageSize, pageToken)
	ret0, _ := ret[0].(biz.ListSummariesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSourceSummaries indicates an expected call of ListSourceSummaries.
func (mr *MockUsecaseMockRecorder) ListSourceSummaries(ctx, sourceID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSourceSummaries", reflect.TypeOf((*MockUsecase)(nil).ListSourceSummaries), ctx, sourceID, pageSize, pageToken)
}

// TriggerSourceSummarize mocks base method.
func (m *MockUsecase) TriggerSourceSummarize(ctx context.Context, sourceID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSourceSummarize", ctx, sourceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TriggerSourceSummarize indicates an expected call of TriggerSourceSummarize.
func (mr *MockUsecaseMockRecorder) TriggerSourceSummarize(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSourceSummarize", reflect.TypeOf((*MockUsecase)(nil).TriggerSourceSummarize), ctx, sourceID)
}
