// Code generated by ent, DO NOT EDIT.

package source

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the source type in the database.
	Label = "source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePosts holds the string denoting the posts edge name in mutations.
	EdgePosts = "posts"
	// EdgeSourceSummaries holds the string denoting the source_summaries edge name in mutations.
	EdgeSourceSummaries = "source_summaries"
	// EdgeSummaryEvents holds the string denoting the summary_events edge name in mutations.
	EdgeSummaryEvents = "summary_events"
	// Table holds the table name of the source in the database.
	Table = "sources"
	// PostsTable is the table that holds the posts relation/edge.
	PostsTable = "posts"
	// PostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostsInverseTable = "posts"
	// PostsColumn is the table column denoting the posts relation/edge.
	PostsColumn = "source_id"
	// SourceSummariesTable is the table that holds the source_summaries relation/edge.
	SourceSummariesTable = "summaries"
	// SourceSummariesInverseTable is the table name for the Summary entity.
	// It exists in this package in order to avoid circular dependency with the "summary" package.
	SourceSummariesInverseTable = "summaries"
	// SourceSummariesColumn is the table column denoting the source_summaries relation/edge.
	SourceSummariesColumn = "source_id"
	// SummaryEventsTable is the table that holds the summary_events relation/edge.
	SummaryEventsTable = "summary_events"
	// SummaryEventsInverseTable is the table name for the SummaryEvent entity.
	// It exists in this package in order to avoid circular dependency with the "summaryevent" package.
	SummaryEventsInverseTable = "summary_events"
	// SummaryEventsColumn is the table column denoting the summary_events relation/edge.
	SummaryEventsColumn = "source_summary_events"
)

// Columns holds all SQL columns for source fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldConfig,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Source queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPostsCount orders the results by posts count.
func ByPostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPostsStep(), opts...)
	}
}

// ByPosts orders the results by posts terms.
func ByPosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySourceSummariesCount orders the results by source_summaries count.
func BySourceSummariesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSourceSummariesStep(), opts...)
	}
}

// BySourceSummaries orders the results by source_summaries terms.
func BySourceSummaries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceSummariesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySummaryEventsCount orders the results by summary_events count.
func BySummaryEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSummaryEventsStep(), opts...)
	}
}

// BySummaryEvents orders the results by summary_events terms.
func BySummaryEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSummaryEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
	)
}
func newSourceSummariesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceSummariesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SourceSummariesTable, SourceSummariesColumn),
	)
}
func newSummaryEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SummaryEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SummaryEventsTable, SummaryEventsColumn),
	)
}
