// Code generated by MockGen. DO NOT EDIT.
// Source: internal/biz/summary.go
//
// Generated by this command:
//
//	mockgen -source=internal/biz/summary.go -destination=internal/biz/mock/mock_summary.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	biz "github.com/4itosik/feedium/internal/biz"
	gomock "go.uber.org/mock/gomock"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// InTx mocks base method.
func (m *MockTxManager) InTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTx indicates an expected call of InTx.
func (mr *MockTxManagerMockRecorder) InTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTx", reflect.TypeOf((*MockTxManager)(nil).InTx), ctx, fn)
}

// MockSummaryRepo is a mock of SummaryRepo interface.
type MockSummaryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryRepoMockRecorder
	isgomock struct{}
}

// MockSummaryRepoMockRecorder is the mock recorder for MockSummaryRepo.
type MockSummaryRepoMockRecorder struct {
	mock *MockSummaryRepo
}

// NewMockSummaryRepo creates a new mock instance.
func NewMockSummaryRepo(ctrl *gomock.Controller) *MockSummaryRepo {
	mock := &MockSummaryRepo{ctrl: ctrl}
	mock.recorder = &MockSummaryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryRepo) EXPECT() *MockSummaryRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSummaryRepo) Get(ctx context.Context, id string) (biz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(biz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSummaryRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSummaryRepo)(nil).Get), ctx, id)
}

// GetLastBySource mocks base method.
func (m *MockSummaryRepo) GetLastBySource(ctx context.Context, sourceID string) (*biz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastBySource", ctx, sourceID)
	ret0, _ := ret[0].(*biz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastBySource indicates an expected call of GetLastBySource.
func (mr *MockSummaryRepoMockRecorder) GetLastBySource(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastBySource", reflect.TypeOf((*MockSummaryRepo)(nil).GetLastBySource), ctx, sourceID)
}

// ListByPost mocks base method.
func (m *MockSummaryRepo) ListByPost(ctx context.Context, postID string) ([]biz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPost", ctx, postID)
	ret0, _ := ret[0].([]biz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPost indicates an expected call of ListByPost.
func (mr *MockSummaryRepoMockRecorder) ListByPost(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPost", reflect.TypeOf((*MockSummaryRepo)(nil).ListByPost), ctx, postID)
}

// ListBySource mocks base method.
func (m *MockSummaryRepo) ListBySource(ctx context.Context, sourceID string, pageSize int, pageToken string) (biz.ListSummariesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySource", ctx, sourceID, pageSize, pageToken)
	ret0, _ := ret[0].(biz.ListSummariesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySource indicates an expected call of ListBySource.
func (mr *MockSummaryRepoMockRecorder) ListBySource(ctx, sourceID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySource", reflect.TypeOf((*MockSummaryRepo)(nil).ListBySource), ctx, sourceID, pageSize, pageToken)
}

// Save mocks base method.
func (m *MockSummaryRepo) Save(ctx context.Context, summary biz.Summary) (biz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, summary)
	ret0, _ := ret[0].(biz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSummaryRepoMockRecorder) Save(ctx, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSummaryRepo)(nil).Save), ctx, summary)
}

// MockSummaryOutboxRepo is a mock of SummaryOutboxRepo interface.
type MockSummaryOutboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryOutboxRepoMockRecorder
	isgomock struct{}
}

// MockSummaryOutboxRepoMockRecorder is the mock recorder for MockSummaryOutboxRepo.
type MockSummaryOutboxRepoMockRecorder struct {
	mock *MockSummaryOutboxRepo
}

// NewMockSummaryOutboxRepo creates a new mock instance.
func NewMockSummaryOutboxRepo(ctrl *gomock.Controller) *MockSummaryOutboxRepo {
	mock := &MockSummaryOutboxRepo{ctrl: ctrl}
	mock.recorder = &MockSummaryOutboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryOutboxRepo) EXPECT() *MockSummaryOutboxRepoMockRecorder {
	return m.recorder
}

// ClaimOne mocks base method.
func (m *MockSummaryOutboxRepo) ClaimOne(ctx context.Context, workerID string, leaseTTL time.Duration) (biz.SummaryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOne", ctx, workerID, leaseTTL)
	ret0, _ := ret[0].(biz.SummaryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOne indicates an expected call of ClaimOne.
func (mr *MockSummaryOutboxRepoMockRecorder) ClaimOne(ctx, workerID, leaseTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOne", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).ClaimOne), ctx, workerID, leaseTTL)
}

// ExtendLease mocks base method.
func (m *MockSummaryOutboxRepo) ExtendLease(ctx context.Context, eventID, workerID string, leaseTTL time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendLease", ctx, eventID, workerID, leaseTTL)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendLease indicates an expected call of ExtendLease.
func (mr *MockSummaryOutboxRepoMockRecorder) ExtendLease(ctx, eventID, workerID, leaseTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendLease", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).ExtendLease), ctx, eventID, workerID, leaseTTL)
}

// FinalizeWithLease mocks base method.
func (m *MockSummaryOutboxRepo) FinalizeWithLease(ctx context.Context, eventID, workerID string, status biz.SummaryEventStatus, summaryID, errText *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeWithLease", ctx, eventID, workerID, status, summaryID, errText)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeWithLease indicates an expected call of FinalizeWithLease.
func (mr *MockSummaryOutboxRepoMockRecorder) FinalizeWithLease(ctx, eventID, workerID, status, summaryID, errText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeWithLease", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).FinalizeWithLease), ctx, eventID, workerID, status, summaryID, errText)
}

// Get mocks base method.
func (m *MockSummaryOutboxRepo) Get(ctx context.Context, id string) (biz.SummaryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(biz.SummaryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSummaryOutboxRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).Get), ctx, id)
}

// HasActiveEvent mocks base method.
func (m *MockSummaryOutboxRepo) HasActiveEvent(ctx context.Context, sourceID string, eventType biz.SummaryEventType) (bool, *biz.SummaryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveEvent", ctx, sourceID, eventType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*biz.SummaryEvent)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HasActiveEvent indicates an expected call of HasActiveEvent.
func (mr *MockSummaryOutboxRepoMockRecorder) HasActiveEvent(ctx, sourceID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveEvent", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).HasActiveEvent), ctx, sourceID, eventType)
}

// ListLeaseExpired mocks base method.
func (m *MockSummaryOutboxRepo) ListLeaseExpired(ctx context.Context, grace time.Duration, limit int) ([]biz.SummaryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLeaseExpired", ctx, grace, limit)
	ret0, _ := ret[0].([]biz.SummaryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLeaseExpired indicates an expected call of ListLeaseExpired.
func (mr *MockSummaryOutboxRepoMockRecorder) ListLeaseExpired(ctx, grace, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLeaseExpired", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).ListLeaseExpired), ctx, grace, limit)
}

// MarkForRetry mocks base method.
func (m *MockSummaryOutboxRepo) MarkForRetry(ctx context.Context, eventID, workerID string, retryAt time.Time, errText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkForRetry", ctx, eventID, workerID, retryAt, errText)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkForRetry indicates an expected call of MarkForRetry.
func (mr *MockSummaryOutboxRepoMockRecorder) MarkForRetry(ctx, eventID, workerID, retryAt, errText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkForRetry", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).MarkForRetry), ctx, eventID, workerID, retryAt, errText)
}

// Save mocks base method.
func (m *MockSummaryOutboxRepo) Save(ctx context.Context, event biz.SummaryEvent) (biz.SummaryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, event)
	ret0, _ := ret[0].(biz.SummaryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSummaryOutboxRepoMockRecorder) Save(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).Save), ctx, event)
}

// UpdateStatus mocks base method.
func (m *MockSummaryOutboxRepo) UpdateStatus(ctx context.Context, id string, status biz.SummaryEventStatus, summaryID, errText *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, summaryID, errText)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSummaryOutboxRepoMockRecorder) UpdateStatus(ctx, id, status, summaryID, errText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSummaryOutboxRepo)(nil).UpdateStatus), ctx, id, status, summaryID, errText)
}

// MockLLMProvider is a mock of LLMProvider interface.
type MockLLMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderMockRecorder
	isgomock struct{}
}

// MockLLMProviderMockRecorder is the mock recorder for MockLLMProvider.
type MockLLMProviderMockRecorder struct {
	mock *MockLLMProvider
}

// NewMockLLMProvider creates a new mock instance.
func NewMockLLMProvider(ctrl *gomock.Controller) *MockLLMProvider {
	mock := &MockLLMProvider{ctrl: ctrl}
	mock.recorder = &MockLLMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProvider) EXPECT() *MockLLMProviderMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockLLMProvider) Summarize(ctx context.Context, text string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, text)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockLLMProviderMockRecorder) Summarize(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockLLMProvider)(nil).Summarize), ctx, text)
}
