// Code generated by ent, DO NOT EDIT.

package summaryevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/4itosik/feedium/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldID, id))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldPostID, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldSourceID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldEventType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldStatus, v))
}

// SummaryID applies equality check predicate on the "summary_id" field. It's identical to SummaryIDEQ.
func SummaryID(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldSummaryID, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldPostID, v))
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldPostID, v))
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldPostID, v))
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldPostID, v))
}

// PostIDIsNil applies the IsNil predicate on the "post_id" field.
func PostIDIsNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIsNull(FieldPostID))
}

// PostIDNotNil applies the NotNil predicate on the "post_id" field.
func PostIDNotNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotNull(FieldPostID))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldSourceID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldContainsFold(FieldEventType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldContainsFold(FieldStatus, v))
}

// SummaryIDEQ applies the EQ predicate on the "summary_id" field.
func SummaryIDEQ(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldSummaryID, v))
}

// SummaryIDNEQ applies the NEQ predicate on the "summary_id" field.
func SummaryIDNEQ(v uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldSummaryID, v))
}

// SummaryIDIn applies the In predicate on the "summary_id" field.
func SummaryIDIn(vs ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldSummaryID, vs...))
}

// SummaryIDNotIn applies the NotIn predicate on the "summary_id" field.
func SummaryIDNotIn(vs ...uuid.UUID) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldSummaryID, vs...))
}

// SummaryIDIsNil applies the IsNil predicate on the "summary_id" field.
func SummaryIDIsNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIsNull(FieldSummaryID))
}

// SummaryIDNotNil applies the NotNil predicate on the "summary_id" field.
func SummaryIDNotNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotNull(FieldSummaryID))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.FieldNotNull(FieldProcessedAt))
}

// HasSummary applies the HasEdge predicate on the "summary" edge.
func HasSummary() predicate.SummaryEvent {
	return predicate.SummaryEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SummaryTable, SummaryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSummaryWith applies the HasEdge predicate on the "summary" edge with a given conditions (other predicates).
func HasSummaryWith(preds ...predicate.Summary) predicate.SummaryEvent {
	return predicate.SummaryEvent(func(s *sql.Selector) {
		step := newSummaryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SummaryEvent) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SummaryEvent) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SummaryEvent) predicate.SummaryEvent {
	return predicate.SummaryEvent(sql.NotPredicates(p))
}
