// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/feedium/post.proto

package feedium

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostService_V1CreatePost_FullMethodName = "/feedium.PostService/V1CreatePost"
	PostService_V1UpdatePost_FullMethodName = "/feedium.PostService/V1UpdatePost"
	PostService_V1DeletePost_FullMethodName = "/feedium.PostService/V1DeletePost"
	PostService_V1GetPost_FullMethodName    = "/feedium.PostService/V1GetPost"
	PostService_V1ListPosts_FullMethodName  = "/feedium.PostService/V1ListPosts"
)

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostServiceClient interface {
	V1CreatePost(ctx context.Context, in *V1CreatePostRequest, opts ...grpc.CallOption) (*V1CreatePostResponse, error)
	V1UpdatePost(ctx context.Context, in *V1UpdatePostRequest, opts ...grpc.CallOption) (*V1UpdatePostResponse, error)
	V1DeletePost(ctx context.Context, in *V1DeletePostRequest, opts ...grpc.CallOption) (*V1DeletePostResponse, error)
	V1GetPost(ctx context.Context, in *V1GetPostRequest, opts ...grpc.CallOption) (*V1GetPostResponse, error)
	V1ListPosts(ctx context.Context, in *V1ListPostsRequest, opts ...grpc.CallOption) (*V1ListPostsResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) V1CreatePost(ctx context.Context, in *V1CreatePostRequest, opts ...grpc.CallOption) (*V1CreatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1CreatePostResponse)
	err := c.cc.Invoke(ctx, PostService_V1CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) V1UpdatePost(ctx context.Context, in *V1UpdatePostRequest, opts ...grpc.CallOption) (*V1UpdatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1UpdatePostResponse)
	err := c.cc.Invoke(ctx, PostService_V1UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) V1DeletePost(ctx context.Context, in *V1DeletePostRequest, opts ...grpc.CallOption) (*V1DeletePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1DeletePostResponse)
	err := c.cc.Invoke(ctx, PostService_V1DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) V1GetPost(ctx context.Context, in *V1GetPostRequest, opts ...grpc.CallOption) (*V1GetPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1GetPostResponse)
	err := c.cc.Invoke(ctx, PostService_V1GetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) V1ListPosts(ctx context.Context, in *V1ListPostsRequest, opts ...grpc.CallOption) (*V1ListPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1ListPostsResponse)
	err := c.cc.Invoke(ctx, PostService_V1ListPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
// All implementations must embed UnimplementedPostServiceServer
// for forward compatibility.
type PostServiceServer interface {
	V1CreatePost(context.Context, *V1CreatePostRequest) (*V1CreatePostResponse, error)
	V1UpdatePost(context.Context, *V1UpdatePostRequest) (*V1UpdatePostResponse, error)
	V1DeletePost(context.Context, *V1DeletePostRequest) (*V1DeletePostResponse, error)
	V1GetPost(context.Context, *V1GetPostRequest) (*V1GetPostResponse, error)
	V1ListPosts(context.Context, *V1ListPostsRequest) (*V1ListPostsResponse, error)
	mustEmbedUnimplementedPostServiceServer()
}

// UnimplementedPostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostServiceServer struct{}

func (UnimplementedPostServiceServer) V1CreatePost(context.Context, *V1CreatePostRequest) (*V1CreatePostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1CreatePost not implemented")
}
func (UnimplementedPostServiceServer) V1UpdatePost(context.Context, *V1UpdatePostRequest) (*V1UpdatePostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1UpdatePost not implemented")
}
func (UnimplementedPostServiceServer) V1DeletePost(context.Context, *V1DeletePostRequest) (*V1DeletePostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1DeletePost not implemented")
}
func (UnimplementedPostServiceServer) V1GetPost(context.Context, *V1GetPostRequest) (*V1GetPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1GetPost not implemented")
}
func (UnimplementedPostServiceServer) V1ListPosts(context.Context, *V1ListPostsRequest) (*V1ListPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1ListPosts not implemented")
}
func (UnimplementedPostServiceServer) mustEmbedUnimplementedPostServiceServer() {}
func (UnimplementedPostServiceServer) testEmbeddedByValue()                     {}

// UnsafePostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostServiceServer will
// result in compilation errors.
type UnsafePostServiceServer interface {
	mustEmbedUnimplementedPostServiceServer()
}

func RegisterPostServiceServer(s grpc.ServiceRegistrar, srv PostServiceServer) {
	// If the following call panics, it indicates UnimplementedPostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostService_ServiceDesc, srv)
}

func _PostService_V1CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).V1CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_V1CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).V1CreatePost(ctx, req.(*V1CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_V1UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).V1UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_V1UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).V1UpdatePost(ctx, req.(*V1UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_V1DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).V1DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_V1DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).V1DeletePost(ctx, req.(*V1DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_V1GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).V1GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_V1GetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).V1GetPost(ctx, req.(*V1GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_V1ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).V1ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_V1ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).V1ListPosts(ctx, req.(*V1ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostService_ServiceDesc is the grpc.ServiceDesc for PostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feedium.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "V1CreatePost",
			Handler:    _PostService_V1CreatePost_Handler,
		},
		{
			MethodName: "V1UpdatePost",
			Handler:    _PostService_V1UpdatePost_Handler,
		},
		{
			MethodName: "V1DeletePost",
			Handler:    _PostService_V1DeletePost_Handler,
		},
		{
			MethodName: "V1GetPost",
			Handler:    _PostService_V1GetPost_Handler,
		},
		{
			MethodName: "V1ListPosts",
			Handler:    _PostService_V1ListPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/feedium/post.proto",
}
