// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/feedium/post.proto

package feedium

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPostServiceV1CreatePost = "/feedium.PostService/V1CreatePost"
const OperationPostServiceV1DeletePost = "/feedium.PostService/V1DeletePost"
const OperationPostServiceV1GetPost = "/feedium.PostService/V1GetPost"
const OperationPostServiceV1ListPosts = "/feedium.PostService/V1ListPosts"
const OperationPostServiceV1UpdatePost = "/feedium.PostService/V1UpdatePost"

type PostServiceHTTPServer interface {
	V1CreatePost(context.Context, *V1CreatePostRequest) (*V1CreatePostResponse, error)
	V1DeletePost(context.Context, *V1DeletePostRequest) (*V1DeletePostResponse, error)
	V1GetPost(context.Context, *V1GetPostRequest) (*V1GetPostResponse, error)
	V1ListPosts(context.Context, *V1ListPostsRequest) (*V1ListPostsResponse, error)
	V1UpdatePost(context.Context, *V1UpdatePostRequest) (*V1UpdatePostResponse, error)
}

func RegisterPostServiceHTTPServer(s *http.Server, srv PostServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/posts", _PostService_V1CreatePost0_HTTP_Handler(srv))
	r.PUT("/v1/posts/{id}", _PostService_V1UpdatePost0_HTTP_Handler(srv))
	r.DELETE("/v1/posts/{id}", _PostService_V1DeletePost0_HTTP_Handler(srv))
	r.GET("/v1/posts/{id}", _PostService_V1GetPost0_HTTP_Handler(srv))
	r.GET("/v1/posts", _PostService_V1ListPosts0_HTTP_Handler(srv))
}

func _PostService_V1CreatePost0_HTTP_Handler(srv PostServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1CreatePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostServiceV1CreatePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1CreatePost(ctx, req.(*V1CreatePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1CreatePostResponse)
		return ctx.Result(200, reply)
	}
}

func _PostService_V1UpdatePost0_HTTP_Handler(srv PostServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1UpdatePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostServiceV1UpdatePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1UpdatePost(ctx, req.(*V1UpdatePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1UpdatePostResponse)
		return ctx.Result(200, reply)
	}
}

func _PostService_V1DeletePost0_HTTP_Handler(srv PostServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1DeletePostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostServiceV1DeletePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1DeletePost(ctx, req.(*V1DeletePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1DeletePostResponse)
		return ctx.Result(200, reply)
	}
}

func _PostService_V1GetPost0_HTTP_Handler(srv PostServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1GetPostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostServiceV1GetPost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1GetPost(ctx, req.(*V1GetPostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1GetPostResponse)
		return ctx.Result(200, reply)
	}
}

func _PostService_V1ListPosts0_HTTP_Handler(srv PostServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1ListPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostServiceV1ListPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1ListPosts(ctx, req.(*V1ListPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1ListPostsResponse)
		return ctx.Result(200, reply)
	}
}

type PostServiceHTTPClient interface {
	V1CreatePost(ctx context.Context, req *V1CreatePostRequest, opts ...http.CallOption) (rsp *V1CreatePostResponse, err error)
	V1DeletePost(ctx context.Context, req *V1DeletePostRequest, opts ...http.CallOption) (rsp *V1DeletePostResponse, err error)
	V1GetPost(ctx context.Context, req *V1GetPostRequest, opts ...http.CallOption) (rsp *V1GetPostResponse, err error)
	V1ListPosts(ctx context.Context, req *V1ListPostsRequest, opts ...http.CallOption) (rsp *V1ListPostsResponse, err error)
	V1UpdatePost(ctx context.Context, req *V1UpdatePostRequest, opts ...http.CallOption) (rsp *V1UpdatePostResponse, err error)
}

type PostServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPostServiceHTTPClient(client *http.Client) PostServiceHTTPClient {
	return &PostServiceHTTPClientImpl{client}
}

func (c *PostServiceHTTPClientImpl) V1CreatePost(ctx context.Context, in *V1CreatePostRequest, opts ...http.CallOption) (*V1CreatePostResponse, error) {
	var out V1CreatePostResponse
	pattern := "/v1/posts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPostServiceV1CreatePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PostServiceHTTPClientImpl) V1DeletePost(ctx context.Context, in *V1DeletePostRequest, opts ...http.CallOption) (*V1DeletePostResponse, error) {
	var out V1DeletePostResponse
	pattern := "/v1/posts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostServiceV1DeletePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PostServiceHTTPClientImpl) V1GetPost(ctx context.Context, in *V1GetPostRequest, opts ...http.CallOption) (*V1GetPostResponse, error) {
	var out V1GetPostResponse
	pattern := "/v1/posts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostServiceV1GetPost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PostServiceHTTPClientImpl) V1ListPosts(ctx context.Context, in *V1ListPostsRequest, opts ...http.CallOption) (*V1ListPostsResponse, error) {
	var out V1ListPostsResponse
	pattern := "/v1/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostServiceV1ListPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PostServiceHTTPClientImpl) V1UpdatePost(ctx context.Context, in *V1UpdatePostRequest, opts ...http.CallOption) (*V1UpdatePostResponse, error) {
	var out V1UpdatePostResponse
	pattern := "/v1/posts/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPostServiceV1UpdatePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
