// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/feedium/source.proto

package feedium

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSourceServiceV1CreateSource = "/feedium.SourceService/V1CreateSource"
const OperationSourceServiceV1DeleteSource = "/feedium.SourceService/V1DeleteSource"
const OperationSourceServiceV1GetSource = "/feedium.SourceService/V1GetSource"
const OperationSourceServiceV1ListSources = "/feedium.SourceService/V1ListSources"
const OperationSourceServiceV1UpdateSource = "/feedium.SourceService/V1UpdateSource"

type SourceServiceHTTPServer interface {
	V1CreateSource(context.Context, *V1CreateSourceRequest) (*V1CreateSourceResponse, error)
	V1DeleteSource(context.Context, *V1DeleteSourceRequest) (*V1DeleteSourceResponse, error)
	V1GetSource(context.Context, *V1GetSourceRequest) (*V1GetSourceResponse, error)
	V1ListSources(context.Context, *V1ListSourcesRequest) (*V1ListSourcesResponse, error)
	V1UpdateSource(context.Context, *V1UpdateSourceRequest) (*V1UpdateSourceResponse, error)
}

func RegisterSourceServiceHTTPServer(s *http.Server, srv SourceServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/sources", _SourceService_V1CreateSource0_HTTP_Handler(srv))
	r.PUT("/v1/sources/{id}", _SourceService_V1UpdateSource0_HTTP_Handler(srv))
	r.DELETE("/v1/sources/{id}", _SourceService_V1DeleteSource0_HTTP_Handler(srv))
	r.GET("/v1/sources", _SourceService_V1ListSources0_HTTP_Handler(srv))
	r.GET("/v1/sources/{id}", _SourceService_V1GetSource0_HTTP_Handler(srv))
}

func _SourceService_V1CreateSource0_HTTP_Handler(srv SourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1CreateSourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSourceServiceV1CreateSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1CreateSource(ctx, req.(*V1CreateSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1CreateSourceResponse)
		return ctx.Result(200, reply)
	}
}

func _SourceService_V1UpdateSource0_HTTP_Handler(srv SourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1UpdateSourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSourceServiceV1UpdateSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1UpdateSource(ctx, req.(*V1UpdateSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1UpdateSourceResponse)
		return ctx.Result(200, reply)
	}
}

func _SourceService_V1DeleteSource0_HTTP_Handler(srv SourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1DeleteSourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSourceServiceV1DeleteSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1DeleteSource(ctx, req.(*V1DeleteSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1DeleteSourceResponse)
		return ctx.Result(200, reply)
	}
}

func _SourceService_V1ListSources0_HTTP_Handler(srv SourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1ListSourcesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSourceServiceV1ListSources)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1ListSources(ctx, req.(*V1ListSourcesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1ListSourcesResponse)
		return ctx.Result(200, reply)
	}
}

func _SourceService_V1GetSource0_HTTP_Handler(srv SourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1GetSourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSourceServiceV1GetSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1GetSource(ctx, req.(*V1GetSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1GetSourceResponse)
		return ctx.Result(200, reply)
	}
}

type SourceServiceHTTPClient interface {
	V1CreateSource(ctx context.Context, req *V1CreateSourceRequest, opts ...http.CallOption) (rsp *V1CreateSourceResponse, err error)
	V1DeleteSource(ctx context.Context, req *V1DeleteSourceRequest, opts ...http.CallOption) (rsp *V1DeleteSourceResponse, err error)
	V1GetSource(ctx context.Context, req *V1GetSourceRequest, opts ...http.CallOption) (rsp *V1GetSourceResponse, err error)
	V1ListSources(ctx context.Context, req *V1ListSourcesRequest, opts ...http.CallOption) (rsp *V1ListSourcesResponse, err error)
	V1UpdateSource(ctx context.Context, req *V1UpdateSourceRequest, opts ...http.CallOption) (rsp *V1UpdateSourceResponse, err error)
}

type SourceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSourceServiceHTTPClient(client *http.Client) SourceServiceHTTPClient {
	return &SourceServiceHTTPClientImpl{client}
}

func (c *SourceServiceHTTPClientImpl) V1CreateSource(ctx context.Context, in *V1CreateSourceRequest, opts ...http.CallOption) (*V1CreateSourceResponse, error) {
	var out V1CreateSourceResponse
	pattern := "/v1/sources"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSourceServiceV1CreateSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SourceServiceHTTPClientImpl) V1DeleteSource(ctx context.Context, in *V1DeleteSourceRequest, opts ...http.CallOption) (*V1DeleteSourceResponse, error) {
	var out V1DeleteSourceResponse
	pattern := "/v1/sources/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSourceServiceV1DeleteSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SourceServiceHTTPClientImpl) V1GetSource(ctx context.Context, in *V1GetSourceRequest, opts ...http.CallOption) (*V1GetSourceResponse, error) {
	var out V1GetSourceResponse
	pattern := "/v1/sources/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSourceServiceV1GetSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SourceServiceHTTPClientImpl) V1ListSources(ctx context.Context, in *V1ListSourcesRequest, opts ...http.CallOption) (*V1ListSourcesResponse, error) {
	var out V1ListSourcesResponse
	pattern := "/v1/sources"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSourceServiceV1ListSources))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SourceServiceHTTPClientImpl) V1UpdateSource(ctx context.Context, in *V1UpdateSourceRequest, opts ...http.CallOption) (*V1UpdateSourceResponse, error) {
	var out V1UpdateSourceResponse
	pattern := "/v1/sources/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSourceServiceV1UpdateSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
