// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/feedium/summary.proto

package feedium

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SummaryService_V1SummarizeSource_FullMethodName     = "/feedium.SummaryService/V1SummarizeSource"
	SummaryService_V1GetSummaryEvent_FullMethodName     = "/feedium.SummaryService/V1GetSummaryEvent"
	SummaryService_V1ListPostSummaries_FullMethodName   = "/feedium.SummaryService/V1ListPostSummaries"
	SummaryService_V1ListSourceSummaries_FullMethodName = "/feedium.SummaryService/V1ListSourceSummaries"
	SummaryService_V1GetSummary_FullMethodName          = "/feedium.SummaryService/V1GetSummary"
)

// SummaryServiceClient is the client API for SummaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummaryServiceClient interface {
	V1SummarizeSource(ctx context.Context, in *V1SummarizeSourceRequest, opts ...grpc.CallOption) (*V1SummarizeSourceResponse, error)
	V1GetSummaryEvent(ctx context.Context, in *V1GetSummaryEventRequest, opts ...grpc.CallOption) (*V1GetSummaryEventResponse, error)
	V1ListPostSummaries(ctx context.Context, in *V1ListPostSummariesRequest, opts ...grpc.CallOption) (*V1ListPostSummariesResponse, error)
	V1ListSourceSummaries(ctx context.Context, in *V1ListSourceSummariesRequest, opts ...grpc.CallOption) (*V1ListSourceSummariesResponse, error)
	V1GetSummary(ctx context.Context, in *V1GetSummaryRequest, opts ...grpc.CallOption) (*V1GetSummaryResponse, error)
}

type summaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSummaryServiceClient(cc grpc.ClientConnInterface) SummaryServiceClient {
	return &summaryServiceClient{cc}
}

func (c *summaryServiceClient) V1SummarizeSource(ctx context.Context, in *V1SummarizeSourceRequest, opts ...grpc.CallOption) (*V1SummarizeSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1SummarizeSourceResponse)
	err := c.cc.Invoke(ctx, SummaryService_V1SummarizeSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryServiceClient) V1GetSummaryEvent(ctx context.Context, in *V1GetSummaryEventRequest, opts ...grpc.CallOption) (*V1GetSummaryEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1GetSummaryEventResponse)
	err := c.cc.Invoke(ctx, SummaryService_V1GetSummaryEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryServiceClient) V1ListPostSummaries(ctx context.Context, in *V1ListPostSummariesRequest, opts ...grpc.CallOption) (*V1ListPostSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1ListPostSummariesResponse)
	err := c.cc.Invoke(ctx, SummaryService_V1ListPostSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryServiceClient) V1ListSourceSummaries(ctx context.Context, in *V1ListSourceSummariesRequest, opts ...grpc.CallOption) (*V1ListSourceSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1ListSourceSummariesResponse)
	err := c.cc.Invoke(ctx, SummaryService_V1ListSourceSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryServiceClient) V1GetSummary(ctx context.Context, in *V1GetSummaryRequest, opts ...grpc.CallOption) (*V1GetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1GetSummaryResponse)
	err := c.cc.Invoke(ctx, SummaryService_V1GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummaryServiceServer is the server API for SummaryService service.
// All implementations must embed UnimplementedSummaryServiceServer
// for forward compatibility.
type SummaryServiceServer interface {
	V1SummarizeSource(context.Context, *V1SummarizeSourceRequest) (*V1SummarizeSourceResponse, error)
	V1GetSummaryEvent(context.Context, *V1GetSummaryEventRequest) (*V1GetSummaryEventResponse, error)
	V1ListPostSummaries(context.Context, *V1ListPostSummariesRequest) (*V1ListPostSummariesResponse, error)
	V1ListSourceSummaries(context.Context, *V1ListSourceSummariesRequest) (*V1ListSourceSummariesResponse, error)
	V1GetSummary(context.Context, *V1GetSummaryRequest) (*V1GetSummaryResponse, error)
	mustEmbedUnimplementedSummaryServiceServer()
}

// UnimplementedSummaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummaryServiceServer struct{}

func (UnimplementedSummaryServiceServer) V1SummarizeSource(context.Context, *V1SummarizeSourceRequest) (*V1SummarizeSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1SummarizeSource not implemented")
}
func (UnimplementedSummaryServiceServer) V1GetSummaryEvent(context.Context, *V1GetSummaryEventRequest) (*V1GetSummaryEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1GetSummaryEvent not implemented")
}
func (UnimplementedSummaryServiceServer) V1ListPostSummaries(context.Context, *V1ListPostSummariesRequest) (*V1ListPostSummariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1ListPostSummaries not implemented")
}
func (UnimplementedSummaryServiceServer) V1ListSourceSummaries(context.Context, *V1ListSourceSummariesRequest) (*V1ListSourceSummariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1ListSourceSummaries not implemented")
}
func (UnimplementedSummaryServiceServer) V1GetSummary(context.Context, *V1GetSummaryRequest) (*V1GetSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method V1GetSummary not implemented")
}
func (UnimplementedSummaryServiceServer) mustEmbedUnimplementedSummaryServiceServer() {}
func (UnimplementedSummaryServiceServer) testEmbeddedByValue()                        {}

// UnsafeSummaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummaryServiceServer will
// result in compilation errors.
type UnsafeSummaryServiceServer interface {
	mustEmbedUnimplementedSummaryServiceServer()
}

func RegisterSummaryServiceServer(s grpc.ServiceRegistrar, srv SummaryServiceServer) {
	// If the following call panics, it indicates UnimplementedSummaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SummaryService_ServiceDesc, srv)
}

func _SummaryService_V1SummarizeSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1SummarizeSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServiceServer).V1SummarizeSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummaryService_V1SummarizeSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServiceServer).V1SummarizeSource(ctx, req.(*V1SummarizeSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SummaryService_V1GetSummaryEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1GetSummaryEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServiceServer).V1GetSummaryEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummaryService_V1GetSummaryEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServiceServer).V1GetSummaryEvent(ctx, req.(*V1GetSummaryEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SummaryService_V1ListPostSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1ListPostSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServiceServer).V1ListPostSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummaryService_V1ListPostSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServiceServer).V1ListPostSummaries(ctx, req.(*V1ListPostSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SummaryService_V1ListSourceSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1ListSourceSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServiceServer).V1ListSourceSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummaryService_V1ListSourceSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServiceServer).V1ListSourceSummaries(ctx, req.(*V1ListSourceSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SummaryService_V1GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServiceServer).V1GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummaryService_V1GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServiceServer).V1GetSummary(ctx, req.(*V1GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SummaryService_ServiceDesc is the grpc.ServiceDesc for SummaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SummaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feedium.SummaryService",
	HandlerType: (*SummaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "V1SummarizeSource",
			Handler:    _SummaryService_V1SummarizeSource_Handler,
		},
		{
			MethodName: "V1GetSummaryEvent",
			Handler:    _SummaryService_V1GetSummaryEvent_Handler,
		},
		{
			MethodName: "V1ListPostSummaries",
			Handler:    _SummaryService_V1ListPostSummaries_Handler,
		},
		{
			MethodName: "V1ListSourceSummaries",
			Handler:    _SummaryService_V1ListSourceSummaries_Handler,
		},
		{
			MethodName: "V1GetSummary",
			Handler:    _SummaryService_V1GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/feedium/summary.proto",
}
