// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/feedium/summary.proto

package feedium

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummaryEventType int32

const (
	SummaryEventType_SUMMARY_EVENT_TYPE_UNSPECIFIED      SummaryEventType = 0
	SummaryEventType_SUMMARY_EVENT_TYPE_SUMMARIZE_POST   SummaryEventType = 1
	SummaryEventType_SUMMARY_EVENT_TYPE_SUMMARIZE_SOURCE SummaryEventType = 2
)

// Enum value maps for SummaryEventType.
var (
	SummaryEventType_name = map[int32]string{
		0: "SUMMARY_EVENT_TYPE_UNSPECIFIED",
		1: "SUMMARY_EVENT_TYPE_SUMMARIZE_POST",
		2: "SUMMARY_EVENT_TYPE_SUMMARIZE_SOURCE",
	}
	SummaryEventType_value = map[string]int32{
		"SUMMARY_EVENT_TYPE_UNSPECIFIED":      0,
		"SUMMARY_EVENT_TYPE_SUMMARIZE_POST":   1,
		"SUMMARY_EVENT_TYPE_SUMMARIZE_SOURCE": 2,
	}
)

func (x SummaryEventType) Enum() *SummaryEventType {
	p := new(SummaryEventType)
	*p = x
	return p
}

func (x SummaryEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SummaryEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_feedium_summary_proto_enumTypes[0].Descriptor()
}

func (SummaryEventType) Type() protoreflect.EnumType {
	return &file_api_feedium_summary_proto_enumTypes[0]
}

func (x SummaryEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SummaryEventType.Descriptor instead.
func (SummaryEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{0}
}

type SummaryEventStatus int32

const (
	SummaryEventStatus_SUMMARY_EVENT_STATUS_UNSPECIFIED SummaryEventStatus = 0
	SummaryEventStatus_SUMMARY_EVENT_STATUS_PENDING     SummaryEventStatus = 1
	SummaryEventStatus_SUMMARY_EVENT_STATUS_PROCESSING  SummaryEventStatus = 2
	SummaryEventStatus_SUMMARY_EVENT_STATUS_COMPLETED   SummaryEventStatus = 3
	SummaryEventStatus_SUMMARY_EVENT_STATUS_FAILED      SummaryEventStatus = 4
	SummaryEventStatus_SUMMARY_EVENT_STATUS_EXPIRED     SummaryEventStatus = 5
)

// Enum value maps for SummaryEventStatus.
var (
	SummaryEventStatus_name = map[int32]string{
		0: "SUMMARY_EVENT_STATUS_UNSPECIFIED",
		1: "SUMMARY_EVENT_STATUS_PENDING",
		2: "SUMMARY_EVENT_STATUS_PROCESSING",
		3: "SUMMARY_EVENT_STATUS_COMPLETED",
		4: "SUMMARY_EVENT_STATUS_FAILED",
		5: "SUMMARY_EVENT_STATUS_EXPIRED",
	}
	SummaryEventStatus_value = map[string]int32{
		"SUMMARY_EVENT_STATUS_UNSPECIFIED": 0,
		"SUMMARY_EVENT_STATUS_PENDING":     1,
		"SUMMARY_EVENT_STATUS_PROCESSING":  2,
		"SUMMARY_EVENT_STATUS_COMPLETED":   3,
		"SUMMARY_EVENT_STATUS_FAILED":      4,
		"SUMMARY_EVENT_STATUS_EXPIRED":     5,
	}
)

func (x SummaryEventStatus) Enum() *SummaryEventStatus {
	p := new(SummaryEventStatus)
	*p = x
	return p
}

func (x SummaryEventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SummaryEventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_feedium_summary_proto_enumTypes[1].Descriptor()
}

func (SummaryEventStatus) Type() protoreflect.EnumType {
	return &file_api_feedium_summary_proto_enumTypes[1]
}

func (x SummaryEventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SummaryEventStatus.Descriptor instead.
func (SummaryEventStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{1}
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        *string                `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3,oneof" json:"post_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	WordCount     int32                  `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_api_feedium_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{0}
}

func (x *Summary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Summary) GetPostId() string {
	if x != nil && x.PostId != nil {
		return *x.PostId
	}
	return ""
}

func (x *Summary) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Summary) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Summary) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *Summary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SummaryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	PostId        *string                `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3,oneof" json:"post_id,omitempty"`
	EventType     SummaryEventType       `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=feedium.SummaryEventType" json:"event_type,omitempty"`
	Status        SummaryEventStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=feedium.SummaryEventStatus" json:"status,omitempty"`
	SummaryId     *string                `protobuf:"bytes,6,opt,name=summary_id,json=summaryId,proto3,oneof" json:"summary_id,omitempty"`
	Error         *string                `protobuf:"bytes,7,opt,name=error,proto3,oneof" json:"error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=processed_at,json=processedAt,proto3,oneof" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryEvent) Reset() {
	*x = SummaryEvent{}
	mi := &file_api_feedium_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryEvent) ProtoMessage() {}

func (x *SummaryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryEvent.ProtoReflect.Descriptor instead.
func (*SummaryEvent) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SummaryEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SummaryEvent) GetPostId() string {
	if x != nil && x.PostId != nil {
		return *x.PostId
	}
	return ""
}

func (x *SummaryEvent) GetEventType() SummaryEventType {
	if x != nil {
		return x.EventType
	}
	return SummaryEventType_SUMMARY_EVENT_TYPE_UNSPECIFIED
}

func (x *SummaryEvent) GetStatus() SummaryEventStatus {
	if x != nil {
		return x.Status
	}
	return SummaryEventStatus_SUMMARY_EVENT_STATUS_UNSPECIFIED
}

func (x *SummaryEvent) GetSummaryId() string {
	if x != nil && x.SummaryId != nil {
		return *x.SummaryId
	}
	return ""
}

func (x *SummaryEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *SummaryEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SummaryEvent) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type V1SummarizeSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1SummarizeSourceRequest) Reset() {
	*x = V1SummarizeSourceRequest{}
	mi := &file_api_feedium_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1SummarizeSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1SummarizeSourceRequest) ProtoMessage() {}

func (x *V1SummarizeSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1SummarizeSourceRequest.ProtoReflect.Descriptor instead.
func (*V1SummarizeSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{2}
}

func (x *V1SummarizeSourceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type V1SummarizeSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Existing      bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1SummarizeSourceResponse) Reset() {
	*x = V1SummarizeSourceResponse{}
	mi := &file_api_feedium_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1SummarizeSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1SummarizeSourceResponse) ProtoMessage() {}

func (x *V1SummarizeSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1SummarizeSourceResponse.ProtoReflect.Descriptor instead.
func (*V1SummarizeSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{3}
}

func (x *V1SummarizeSourceResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *V1SummarizeSourceResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

type V1GetSummaryEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1GetSummaryEventRequest) Reset() {
	*x = V1GetSummaryEventRequest{}
	mi := &file_api_feedium_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1GetSummaryEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetSummaryEventRequest) ProtoMessage() {}

func (x *V1GetSummaryEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetSummaryEventRequest.ProtoReflect.Descriptor instead.
func (*V1GetSummaryEventRequest) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{4}
}

func (x *V1GetSummaryEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type V1GetSummaryEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *SummaryEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1GetSummaryEventResponse) Reset() {
	*x = V1GetSummaryEventResponse{}
	mi := &file_api_feedium_summary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1GetSummaryEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetSummaryEventResponse) ProtoMessage() {}

func (x *V1GetSummaryEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetSummaryEventResponse.ProtoReflect.Descriptor instead.
func (*V1GetSummaryEventResponse) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{5}
}

func (x *V1GetSummaryEventResponse) GetEvent() *SummaryEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type V1ListPostSummariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1ListPostSummariesRequest) Reset() {
	*x = V1ListPostSummariesRequest{}
	mi := &file_api_feedium_summary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1ListPostSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ListPostSummariesRequest) ProtoMessage() {}

func (x *V1ListPostSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ListPostSummariesRequest.ProtoReflect.Descriptor instead.
func (*V1ListPostSummariesRequest) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{6}
}

func (x *V1ListPostSummariesRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type V1ListPostSummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*Summary             `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1ListPostSummariesResponse) Reset() {
	*x = V1ListPostSummariesResponse{}
	mi := &file_api_feedium_summary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1ListPostSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ListPostSummariesResponse) ProtoMessage() {}

func (x *V1ListPostSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ListPostSummariesResponse.ProtoReflect.Descriptor instead.
func (*V1ListPostSummariesResponse) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{7}
}

func (x *V1ListPostSummariesResponse) GetSummaries() []*Summary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type V1ListSourceSummariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1ListSourceSummariesRequest) Reset() {
	*x = V1ListSourceSummariesRequest{}
	mi := &file_api_feedium_summary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1ListSourceSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ListSourceSummariesRequest) ProtoMessage() {}

func (x *V1ListSourceSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ListSourceSummariesRequest.ProtoReflect.Descriptor instead.
func (*V1ListSourceSummariesRequest) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{8}
}

func (x *V1ListSourceSummariesRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *V1ListSourceSummariesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *V1ListSourceSummariesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type V1ListSourceSummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*Summary             `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1ListSourceSummariesResponse) Reset() {
	*x = V1ListSourceSummariesResponse{}
	mi := &file_api_feedium_summary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1ListSourceSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ListSourceSummariesResponse) ProtoMessage() {}

func (x *V1ListSourceSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ListSourceSummariesResponse.ProtoReflect.Descriptor instead.
func (*V1ListSourceSummariesResponse) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{9}
}

func (x *V1ListSourceSummariesResponse) GetSummaries() []*Summary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

func (x *V1ListSourceSummariesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type V1GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1GetSummaryRequest) Reset() {
	*x = V1GetSummaryRequest{}
	mi := &file_api_feedium_summary_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetSummaryRequest) ProtoMessage() {}

func (x *V1GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*V1GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{10}
}

func (x *V1GetSummaryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type V1GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *Summary               `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1GetSummaryResponse) Reset() {
	*x = V1GetSummaryResponse{}
	mi := &file_api_feedium_summary_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1GetSummaryResponse) ProtoMessage() {}

func (x *V1GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_feedium_summary_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*V1GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_feedium_summary_proto_rawDescGZIP(), []int{11}
}

func (x *V1GetSummaryResponse) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

var File_api_feedium_summary_proto protoreflect.FileDescriptor

const file_api_feedium_summary_proto_rawDesc = "" +
	"\n" +
	"\x19api/feedium/summary.proto\x12\afeedium\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\aSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\apost_id\x18\x02 \x01(\tH\x00R\x06postId\x88\x01\x01\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05R\twordCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_post_id\"\xbc\x03\n" +
	"\fSummaryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1c\n" +
	"\apost_id\x18\x03 \x01(\tH\x00R\x06postId\x88\x01\x01\x128\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x19.feedium.SummaryEventTypeR\teventType\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.feedium.SummaryEventStatusR\x06status\x12\"\n" +
	"\n" +
	"summary_id\x18\x06 \x01(\tH\x01R\tsummaryId\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\a \x01(\tH\x02R\x05error\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\fprocessed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vprocessedAt\x88\x01\x01B\n" +
	"\n" +
	"\b_post_idB\r\n" +
	"\v_summary_idB\b\n" +
	"\x06_errorB\x0f\n" +
	"\r_processed_at\"7\n" +
	"\x18V1SummarizeSourceRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\"P\n" +
	"\x19V1SummarizeSourceResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting\"*\n" +
	"\x18V1GetSummaryEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x19V1GetSummaryEventResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.feedium.SummaryEventR\x05event\"5\n" +
	"\x1aV1ListPostSummariesRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"M\n" +
	"\x1bV1ListPostSummariesResponse\x12.\n" +
	"\tsummaries\x18\x01 \x03(\v2\x10.feedium.SummaryR\tsummaries\"w\n" +
	"\x1cV1ListSourceSummariesRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"w\n" +
	"\x1dV1ListSourceSummariesResponse\x12.\n" +
	"\tsummaries\x18\x01 \x03(\v2\x10.feedium.SummaryR\tsummaries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"%\n" +
	"\x13V1GetSummaryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x14V1GetSummaryResponse\x12*\n" +
	"\asummary\x18\x01 \x01(\v2\x10.feedium.SummaryR\asummary*\x86\x01\n" +
	"\x10SummaryEventType\x12\"\n" +
	"\x1eSUMMARY_EVENT_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!SUMMARY_EVENT_TYPE_SUMMARIZE_POST\x10\x01\x12'\n" +
	"#SUMMARY_EVENT_TYPE_SUMMARIZE_SOURCE\x10\x02*\xe8\x01\n" +
	"\x12SummaryEventStatus\x12$\n" +
	" SUMMARY_EVENT_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSUMMARY_EVENT_STATUS_PENDING\x10\x01\x12#\n" +
	"\x1fSUMMARY_EVENT_STATUS_PROCESSING\x10\x02\x12\"\n" +
	"\x1eSUMMARY_EVENT_STATUS_COMPLETED\x10\x03\x12\x1f\n" +
	"\x1bSUMMARY_EVENT_STATUS_FAILED\x10\x04\x12 \n" +
	"\x1cSUMMARY_EVENT_STATUS_EXPIRED\x10\x052\x9f\x05\n" +
	"\x0eSummaryService\x12\x88\x01\n" +
	"\x11V1SummarizeSource\x12!.feedium.V1SummarizeSourceRequest\x1a\".feedium.V1SummarizeSourceResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/sources/{source_id}/summarize\x12{\n" +
	"\x11V1GetSummaryEvent\x12!.feedium.V1GetSummaryEventRequest\x1a\".feedium.V1GetSummaryEventResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/summary-events/{id}\x12\x87\x01\n" +
	"\x13V1ListPostSummaries\x12#.feedium.V1ListPostSummariesRequest\x1a$.feedium.V1ListPostSummariesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/posts/{post_id}/summaries\x12\x91\x01\n" +
	"\x15V1ListSourceSummaries\x12%.feedium.V1ListSourceSummariesRequest\x1a&.feedium.V1ListSourceSummariesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/sources/{source_id}/summaries\x12g\n" +
	"\fV1GetSummary\x12\x1c.feedium.V1GetSummaryRequest\x1a\x1d.feedium.V1GetSummaryResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/summaries/{id}B\x1dZ\x1bfeedium/api/feedium;feediumb\x06proto3"

var (
	file_api_feedium_summary_proto_rawDescOnce sync.Once
	file_api_feedium_summary_proto_rawDescData []byte
)

func file_api_feedium_summary_proto_rawDescGZIP() []byte {
	file_api_feedium_summary_proto_rawDescOnce.Do(func() {
		file_api_feedium_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_feedium_summary_proto_rawDesc), len(file_api_feedium_summary_proto_rawDesc)))
	})
	return file_api_feedium_summary_proto_rawDescData
}

var file_api_feedium_summary_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_feedium_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_feedium_summary_proto_goTypes = []any{
	(SummaryEventType)(0),                 // 0: feedium.SummaryEventType
	(SummaryEventStatus)(0),               // 1: feedium.SummaryEventStatus
	(*Summary)(nil),                       // 2: feedium.Summary
	(*SummaryEvent)(nil),                  // 3: feedium.SummaryEvent
	(*V1SummarizeSourceRequest)(nil),      // 4: feedium.V1SummarizeSourceRequest
	(*V1SummarizeSourceResponse)(nil),     // 5: feedium.V1SummarizeSourceResponse
	(*V1GetSummaryEventRequest)(nil),      // 6: feedium.V1GetSummaryEventRequest
	(*V1GetSummaryEventResponse)(nil),     // 7: feedium.V1GetSummaryEventResponse
	(*V1ListPostSummariesRequest)(nil),    // 8: feedium.V1ListPostSummariesRequest
	(*V1ListPostSummariesResponse)(nil),   // 9: feedium.V1ListPostSummariesResponse
	(*V1ListSourceSummariesRequest)(nil),  // 10: feedium.V1ListSourceSummariesRequest
	(*V1ListSourceSummariesResponse)(nil), // 11: feedium.V1ListSourceSummariesResponse
	(*V1GetSummaryRequest)(nil),           // 12: feedium.V1GetSummaryRequest
	(*V1GetSummaryResponse)(nil),          // 13: feedium.V1GetSummaryResponse
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_api_feedium_summary_proto_depIdxs = []int32{
	14, // 0: feedium.Summary.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: feedium.SummaryEvent.event_type:type_name -> feedium.SummaryEventType
	1,  // 2: feedium.SummaryEvent.status:type_name -> feedium.SummaryEventStatus
	14, // 3: feedium.SummaryEvent.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: feedium.SummaryEvent.processed_at:type_name -> google.protobuf.Timestamp
	3,  // 5: feedium.V1GetSummaryEventResponse.event:type_name -> feedium.SummaryEvent
	2,  // 6: feedium.V1ListPostSummariesResponse.summaries:type_name -> feedium.Summary
	2,  // 7: feedium.V1ListSourceSummariesResponse.summaries:type_name -> feedium.Summary
	2,  // 8: feedium.V1GetSummaryResponse.summary:type_name -> feedium.Summary
	4,  // 9: feedium.SummaryService.V1SummarizeSource:input_type -> feedium.V1SummarizeSourceRequest
	6,  // 10: feedium.SummaryService.V1GetSummaryEvent:input_type -> feedium.V1GetSummaryEventRequest
	8,  // 11: feedium.SummaryService.V1ListPostSummaries:input_type -> feedium.V1ListPostSummariesRequest
	10, // 12: feedium.SummaryService.V1ListSourceSummaries:input_type -> feedium.V1ListSourceSummariesRequest
	12, // 13: feedium.SummaryService.V1GetSummary:input_type -> feedium.V1GetSummaryRequest
	5,  // 14: feedium.SummaryService.V1SummarizeSource:output_type -> feedium.V1SummarizeSourceResponse
	7,  // 15: feedium.SummaryService.V1GetSummaryEvent:output_type -> feedium.V1GetSummaryEventResponse
	9,  // 16: feedium.SummaryService.V1ListPostSummaries:output_type -> feedium.V1ListPostSummariesResponse
	11, // 17: feedium.SummaryService.V1ListSourceSummaries:output_type -> feedium.V1ListSourceSummariesResponse
	13, // 18: feedium.SummaryService.V1GetSummary:output_type -> feedium.V1GetSummaryResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_feedium_summary_proto_init() }
func file_api_feedium_summary_proto_init() {
	if File_api_feedium_summary_proto != nil {
		return
	}
	file_api_feedium_summary_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_feedium_summary_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_feedium_summary_proto_rawDesc), len(file_api_feedium_summary_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_feedium_summary_proto_goTypes,
		DependencyIndexes: file_api_feedium_summary_proto_depIdxs,
		EnumInfos:         file_api_feedium_summary_proto_enumTypes,
		MessageInfos:      file_api_feedium_summary_proto_msgTypes,
	}.Build()
	File_api_feedium_summary_proto = out.File
	file_api_feedium_summary_proto_goTypes = nil
	file_api_feedium_summary_proto_depIdxs = nil
}
