// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/feedium/summary.proto

package feedium

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSummaryServiceV1GetSummary = "/feedium.SummaryService/V1GetSummary"
const OperationSummaryServiceV1GetSummaryEvent = "/feedium.SummaryService/V1GetSummaryEvent"
const OperationSummaryServiceV1ListPostSummaries = "/feedium.SummaryService/V1ListPostSummaries"
const OperationSummaryServiceV1ListSourceSummaries = "/feedium.SummaryService/V1ListSourceSummaries"
const OperationSummaryServiceV1SummarizeSource = "/feedium.SummaryService/V1SummarizeSource"

type SummaryServiceHTTPServer interface {
	V1GetSummary(context.Context, *V1GetSummaryRequest) (*V1GetSummaryResponse, error)
	V1GetSummaryEvent(context.Context, *V1GetSummaryEventRequest) (*V1GetSummaryEventResponse, error)
	V1ListPostSummaries(context.Context, *V1ListPostSummariesRequest) (*V1ListPostSummariesResponse, error)
	V1ListSourceSummaries(context.Context, *V1ListSourceSummariesRequest) (*V1ListSourceSummariesResponse, error)
	V1SummarizeSource(context.Context, *V1SummarizeSourceRequest) (*V1SummarizeSourceResponse, error)
}

func RegisterSummaryServiceHTTPServer(s *http.Server, srv SummaryServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/sources/{source_id}/summarize", _SummaryService_V1SummarizeSource0_HTTP_Handler(srv))
	r.GET("/v1/summary-events/{id}", _SummaryService_V1GetSummaryEvent0_HTTP_Handler(srv))
	r.GET("/v1/posts/{post_id}/summaries", _SummaryService_V1ListPostSummaries0_HTTP_Handler(srv))
	r.GET("/v1/sources/{source_id}/summaries", _SummaryService_V1ListSourceSummaries0_HTTP_Handler(srv))
	r.GET("/v1/summaries/{id}", _SummaryService_V1GetSummary0_HTTP_Handler(srv))
}

func _SummaryService_V1SummarizeSource0_HTTP_Handler(srv SummaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1SummarizeSourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSummaryServiceV1SummarizeSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1SummarizeSource(ctx, req.(*V1SummarizeSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1SummarizeSourceResponse)
		return ctx.Result(200, reply)
	}
}

func _SummaryService_V1GetSummaryEvent0_HTTP_Handler(srv SummaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1GetSummaryEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSummaryServiceV1GetSummaryEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1GetSummaryEvent(ctx, req.(*V1GetSummaryEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1GetSummaryEventResponse)
		return ctx.Result(200, reply)
	}
}

func _SummaryService_V1ListPostSummaries0_HTTP_Handler(srv SummaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1ListPostSummariesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSummaryServiceV1ListPostSummaries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1ListPostSummaries(ctx, req.(*V1ListPostSummariesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1ListPostSummariesResponse)
		return ctx.Result(200, reply)
	}
}

func _SummaryService_V1ListSourceSummaries0_HTTP_Handler(srv SummaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1ListSourceSummariesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSummaryServiceV1ListSourceSummaries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1ListSourceSummaries(ctx, req.(*V1ListSourceSummariesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1ListSourceSummariesResponse)
		return ctx.Result(200, reply)
	}
}

func _SummaryService_V1GetSummary0_HTTP_Handler(srv SummaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in V1GetSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSummaryServiceV1GetSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.V1GetSummary(ctx, req.(*V1GetSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*V1GetSummaryResponse)
		return ctx.Result(200, reply)
	}
}

type SummaryServiceHTTPClient interface {
	V1GetSummary(ctx context.Context, req *V1GetSummaryRequest, opts ...http.CallOption) (rsp *V1GetSummaryResponse, err error)
	V1GetSummaryEvent(ctx context.Context, req *V1GetSummaryEventRequest, opts ...http.CallOption) (rsp *V1GetSummaryEventResponse, err error)
	V1ListPostSummaries(ctx context.Context, req *V1ListPostSummariesRequest, opts ...http.CallOption) (rsp *V1ListPostSummariesResponse, err error)
	V1ListSourceSummaries(ctx context.Context, req *V1ListSourceSummariesRequest, opts ...http.CallOption) (rsp *V1ListSourceSummariesResponse, err error)
	V1SummarizeSource(ctx context.Context, req *V1SummarizeSourceRequest, opts ...http.CallOption) (rsp *V1SummarizeSourceResponse, err error)
}

type SummaryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSummaryServiceHTTPClient(client *http.Client) SummaryServiceHTTPClient {
	return &SummaryServiceHTTPClientImpl{client}
}

func (c *SummaryServiceHTTPClientImpl) V1GetSummary(ctx context.Context, in *V1GetSummaryRequest, opts ...http.CallOption) (*V1GetSummaryResponse, error) {
	var out V1GetSummaryResponse
	pattern := "/v1/summaries/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSummaryServiceV1GetSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SummaryServiceHTTPClientImpl) V1GetSummaryEvent(ctx context.Context, in *V1GetSummaryEventRequest, opts ...http.CallOption) (*V1GetSummaryEventResponse, error) {
	var out V1GetSummaryEventResponse
	pattern := "/v1/summary-events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSummaryServiceV1GetSummaryEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SummaryServiceHTTPClientImpl) V1ListPostSummaries(ctx context.Context, in *V1ListPostSummariesRequest, opts ...http.CallOption) (*V1ListPostSummariesResponse, error) {
	var out V1ListPostSummariesResponse
	pattern := "/v1/posts/{post_id}/summaries"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSummaryServiceV1ListPostSummaries))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SummaryServiceHTTPClientImpl) V1ListSourceSummaries(ctx context.Context, in *V1ListSourceSummariesRequest, opts ...http.CallOption) (*V1ListSourceSummariesResponse, error) {
	var out V1ListSourceSummariesResponse
	pattern := "/v1/sources/{source_id}/summaries"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSummaryServiceV1ListSourceSummaries))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SummaryServiceHTTPClientImpl) V1SummarizeSource(ctx context.Context, in *V1SummarizeSourceRequest, opts ...http.CallOption) (*V1SummarizeSourceResponse, error) {
	var out V1SummarizeSourceResponse
	pattern := "/v1/sources/{source_id}/summarize"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSummaryServiceV1SummarizeSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
