// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/4itosik/feedium/internal/conf"
	"github.com/4itosik/feedium/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, logger *slog.Logger) (*kratos.App, func(), error) {
	httpServer := server.NewHTTPServer(confServer, logger)
	grpcServer := server.NewGRPCServer(confServer, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}

// wire.go:

func newApp(logger *slog.Logger, hs *http.Server, gs *grpc.Server) *kratos.App {
	return kratos.New(kratos.Name("feedium"), kratos.Server(hs, gs))
}
