// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/4itosik/feedium/internal/biz"
	"github.com/4itosik/feedium/internal/conf"
	"github.com/4itosik/feedium/internal/data"
	"github.com/4itosik/feedium/internal/server"
	"github.com/4itosik/feedium/internal/service/health"
	"github.com/4itosik/feedium/internal/service/post"
	"github.com/4itosik/feedium/internal/service/source"
	"github.com/4itosik/feedium/internal/service/summary"
	"github.com/4itosik/feedium/internal/task"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, logger *slog.Logger) (*kratos.App, func(), error) {
	confServer := newServerFromBootstrap(bc)
	confData := newDataFromBootstrap(bc)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	healthRepo := data.NewHealthRepo(dataData, logger)
	healthService := health.NewHealthService(healthRepo, logger)
	sourceRepo := data.NewSourceRepo(dataData)
	sourceUsecase := biz.NewSourceUsecase(sourceRepo)
	sourceService := source.NewSourceService(sourceUsecase)
	postRepo := data.NewPostRepo(dataData)
	txManager := data.NewTxManager(dataData)
	summaryOutboxRepo := data.NewSummaryOutboxRepo(dataData)
	postUsecase := biz.NewPostUsecase(postRepo, txManager, summaryOutboxRepo, sourceRepo)
	postService := post.NewPostService(postUsecase)
	summaryRepo := data.NewSummaryRepo(dataData)
	summaryUsecase := biz.NewSummaryUsecase(summaryRepo, summaryOutboxRepo, sourceRepo)
	summaryService := summary.NewSummaryService(summaryUsecase)
	httpServer := server.NewHTTPServer(confServer, healthService, sourceService, postService, summaryService, logger)
	grpcServer := server.NewGRPCServer(confServer, healthService, sourceService, postService, summaryService, logger)
	summaryLLM := newSummaryLLMFromBootstrap(bc)
	openRouterProvider, err := data.NewOpenRouterProvider(summaryLLM, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	confSummary := newSummaryConfigFromBootstrap(bc)
	summaryWorker := task.NewSummaryWorker(summaryOutboxRepo, postRepo, summaryRepo, openRouterProvider, confSummary, logger)
	cronWorker := task.NewCronWorker(summaryOutboxRepo, sourceRepo, summaryRepo, postRepo, confSummary, logger)
	app := newApp(logger, httpServer, grpcServer, summaryWorker, cronWorker)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func newApp(logger *slog.Logger, hs *http.Server, gs *grpc.Server, sw *task.SummaryWorker, cw *task.CronWorker) *kratos.App {
	return kratos.New(kratos.Name("feedium"), kratos.Server(hs, gs, sw, cw))
}

func newDataFromBootstrap(bc *conf.Bootstrap) *conf.Data {
	return bc.GetData()
}

func newServerFromBootstrap(bc *conf.Bootstrap) *conf.Server {
	return bc.GetServer()
}

func newSummaryConfigFromBootstrap(bc *conf.Bootstrap) *conf.Summary {
	return bc.GetSummary()
}

func newSummaryLLMFromBootstrap(bc *conf.Bootstrap) *conf.SummaryLLM {
	if bc.GetSummary() == nil {
		return nil
	}
	return bc.GetSummary().GetLlm()
}
