// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/summary/v1/summary.proto

package summaryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Summary represents a generated summary of one or more posts.
type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PostIds       []string               `protobuf:"bytes,6,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_api_summary_v1_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_api_summary_v1_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_api_summary_v1_summary_proto_rawDescGZIP(), []int{0}
}

func (x *Summary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Summary) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Summary) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Summary) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Summary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Summary) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// GetSummaryByPostRequest requests a summary by post ID.
type GetSummaryByPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryByPostRequest) Reset() {
	*x = GetSummaryByPostRequest{}
	mi := &file_api_summary_v1_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryByPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryByPostRequest) ProtoMessage() {}

func (x *GetSummaryByPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_summary_v1_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryByPostRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryByPostRequest) Descriptor() ([]byte, []int) {
	return file_api_summary_v1_summary_proto_rawDescGZIP(), []int{1}
}

func (x *GetSummaryByPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// GetSummaryByPostResponse returns a summary for a specific post.
type GetSummaryByPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *Summary               `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryByPostResponse) Reset() {
	*x = GetSummaryByPostResponse{}
	mi := &file_api_summary_v1_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryByPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryByPostResponse) ProtoMessage() {}

func (x *GetSummaryByPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_summary_v1_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryByPostResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryByPostResponse) Descriptor() ([]byte, []int) {
	return file_api_summary_v1_summary_proto_rawDescGZIP(), []int{2}
}

func (x *GetSummaryByPostResponse) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// ListSummariesBySourceRequest requests a list of summaries.
type ListSummariesBySourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional source ID filter. If not provided, returns summaries from all sources.
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Maximum number of summaries to return. Must be > 0 and <= 100.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSummariesBySourceRequest) Reset() {
	*x = ListSummariesBySourceRequest{}
	mi := &file_api_summary_v1_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSummariesBySourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSummariesBySourceRequest) ProtoMessage() {}

func (x *ListSummariesBySourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_summary_v1_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSummariesBySourceRequest.ProtoReflect.Descriptor instead.
func (*ListSummariesBySourceRequest) Descriptor() ([]byte, []int) {
	return file_api_summary_v1_summary_proto_rawDescGZIP(), []int{3}
}

func (x *ListSummariesBySourceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ListSummariesBySourceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListSummariesBySourceResponse returns a list of summaries.
type ListSummariesBySourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*Summary             `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSummariesBySourceResponse) Reset() {
	*x = ListSummariesBySourceResponse{}
	mi := &file_api_summary_v1_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSummariesBySourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSummariesBySourceResponse) ProtoMessage() {}

func (x *ListSummariesBySourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_summary_v1_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSummariesBySourceResponse.ProtoReflect.Descriptor instead.
func (*ListSummariesBySourceResponse) Descriptor() ([]byte, []int) {
	return file_api_summary_v1_summary_proto_rawDescGZIP(), []int{4}
}

func (x *ListSummariesBySourceResponse) GetSummaries() []*Summary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

var File_api_summary_v1_summary_proto protoreflect.FileDescriptor

const file_api_summary_v1_summary_proto_rawDesc = "" +
	"\n" +
	"\x1capi/summary/v1/summary.proto\x12\n" +
	"summary.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\aSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bpost_ids\x18\x06 \x03(\tR\apostIds\"2\n" +
	"\x17GetSummaryByPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"I\n" +
	"\x18GetSummaryByPostResponse\x12-\n" +
	"\asummary\x18\x01 \x01(\v2\x13.summary.v1.SummaryR\asummary\"Q\n" +
	"\x1cListSummariesBySourceRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"R\n" +
	"\x1dListSummariesBySourceResponse\x121\n" +
	"\tsummaries\x18\x01 \x03(\v2\x13.summary.v1.SummaryR\tsummaries2\xdd\x01\n" +
	"\x0eSummaryService\x12]\n" +
	"\x10GetSummaryByPost\x12#.summary.v1.GetSummaryByPostRequest\x1a$.summary.v1.GetSummaryByPostResponse\x12l\n" +
	"\x15ListSummariesBySource\x12(.summary.v1.ListSummariesBySourceRequest\x1a).summary.v1.ListSummariesBySourceResponseB\"Z feedium/api/summary/v1;summaryv1b\x06proto3"

var (
	file_api_summary_v1_summary_proto_rawDescOnce sync.Once
	file_api_summary_v1_summary_proto_rawDescData []byte
)

func file_api_summary_v1_summary_proto_rawDescGZIP() []byte {
	file_api_summary_v1_summary_proto_rawDescOnce.Do(func() {
		file_api_summary_v1_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_summary_v1_summary_proto_rawDesc), len(file_api_summary_v1_summary_proto_rawDesc)))
	})
	return file_api_summary_v1_summary_proto_rawDescData
}

var file_api_summary_v1_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_summary_v1_summary_proto_goTypes = []any{
	(*Summary)(nil),                       // 0: summary.v1.Summary
	(*GetSummaryByPostRequest)(nil),       // 1: summary.v1.GetSummaryByPostRequest
	(*GetSummaryByPostResponse)(nil),      // 2: summary.v1.GetSummaryByPostResponse
	(*ListSummariesBySourceRequest)(nil),  // 3: summary.v1.ListSummariesBySourceRequest
	(*ListSummariesBySourceResponse)(nil), // 4: summary.v1.ListSummariesBySourceResponse
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_api_summary_v1_summary_proto_depIdxs = []int32{
	5, // 0: summary.v1.Summary.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: summary.v1.GetSummaryByPostResponse.summary:type_name -> summary.v1.Summary
	0, // 2: summary.v1.ListSummariesBySourceResponse.summaries:type_name -> summary.v1.Summary
	1, // 3: summary.v1.SummaryService.GetSummaryByPost:input_type -> summary.v1.GetSummaryByPostRequest
	3, // 4: summary.v1.SummaryService.ListSummariesBySource:input_type -> summary.v1.ListSummariesBySourceRequest
	2, // 5: summary.v1.SummaryService.GetSummaryByPost:output_type -> summary.v1.GetSummaryByPostResponse
	4, // 6: summary.v1.SummaryService.ListSummariesBySource:output_type -> summary.v1.ListSummariesBySourceResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_summary_v1_summary_proto_init() }
func file_api_summary_v1_summary_proto_init() {
	if File_api_summary_v1_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_summary_v1_summary_proto_rawDesc), len(file_api_summary_v1_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_summary_v1_summary_proto_goTypes,
		DependencyIndexes: file_api_summary_v1_summary_proto_depIdxs,
		MessageInfos:      file_api_summary_v1_summary_proto_msgTypes,
	}.Build()
	File_api_summary_v1_summary_proto = out.File
	file_api_summary_v1_summary_proto_goTypes = nil
	file_api_summary_v1_summary_proto_depIdxs = nil
}
